apiVersion: apps/v1
kind: Deployment
metadata:
  name: boostable
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mem-eater-bst
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mem-eater-bst
    spec:
      #nodeName: node2
      containers:
      - name: mem-eater
        image: ghcr.io/takara9/mem-eater:0.2
        args:
        - "1"
        - "10"
        - "5"
        - "boostable"
        resources:
          requests:
            memory: "100Mi"
            cpu: 0.1
