apiVersion: apps/v1
kind: Deployment
metadata:
  name: besteffort
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mem-eater-be
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mem-eater-be
    spec:
      #nodeName: node2
      containers:
      - name: mem-eater
        image: ghcr.io/takara9/mem-eater:0.2
        args:
        - "1"
        - "10"
        - "5"
        - "besteffort"
